server:
  port: 8080
spring:
  application:
    name: "CrediYA"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
      path: "/h2"
  profiles:
    include: null
adapters:
  mysql:
    url: "r2dbc:mysql://localhost:3306/bd_autenticacion"
    usr: "myroot"
    psw: "myroot123"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

entries:
  web:
    path-base: "${PATH_BASE:/api/v1/credi-ya}"
    path-user: "${PATH_USER:/user}"
    save: "/save"
    exist-by-document: "/document/{documentNumber}"
    path-auth: "/auth"
    login: "/login"
jwt:
  secret: "miClaveSecreta123"
  expiration-ms: 3600000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    co.com.authentication: DEBUG